// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.3
// source: demo1/demo1.proto

package demo1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ChainService_GetFriendFromDB_FullMethodName = "/demo1.chainService/GetFriendFromDB"
)

// ChainServiceClient is the client API for ChainService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChainServiceClient interface {
	GetFriendFromDB(ctx context.Context, in *GetFriendFromDBReq, opts ...grpc.CallOption) (*GetFriendFromDBResp, error)
}

type chainServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChainServiceClient(cc grpc.ClientConnInterface) ChainServiceClient {
	return &chainServiceClient{cc}
}

func (c *chainServiceClient) GetFriendFromDB(ctx context.Context, in *GetFriendFromDBReq, opts ...grpc.CallOption) (*GetFriendFromDBResp, error) {
	out := new(GetFriendFromDBResp)
	err := c.cc.Invoke(ctx, ChainService_GetFriendFromDB_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChainServiceServer is the server API for ChainService service.
// All implementations should embed UnimplementedChainServiceServer
// for forward compatibility
type ChainServiceServer interface {
	GetFriendFromDB(context.Context, *GetFriendFromDBReq) (*GetFriendFromDBResp, error)
}

// UnimplementedChainServiceServer should be embedded to have forward compatible implementations.
type UnimplementedChainServiceServer struct {
}

func (UnimplementedChainServiceServer) GetFriendFromDB(context.Context, *GetFriendFromDBReq) (*GetFriendFromDBResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFriendFromDB not implemented")
}

// UnsafeChainServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChainServiceServer will
// result in compilation errors.
type UnsafeChainServiceServer interface {
	mustEmbedUnimplementedChainServiceServer()
}

func RegisterChainServiceServer(s grpc.ServiceRegistrar, srv ChainServiceServer) {
	s.RegisterService(&ChainService_ServiceDesc, srv)
}

func _ChainService_GetFriendFromDB_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFriendFromDBReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainServiceServer).GetFriendFromDB(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChainService_GetFriendFromDB_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainServiceServer).GetFriendFromDB(ctx, req.(*GetFriendFromDBReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ChainService_ServiceDesc is the grpc.ServiceDesc for ChainService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChainService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "demo1.chainService",
	HandlerType: (*ChainServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFriendFromDB",
			Handler:    _ChainService_GetFriendFromDB_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "demo1/demo1.proto",
}
