// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.8
// source: demo1/demo1.proto

package demo1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommonResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrCode int32  `protobuf:"varint,1,opt,name=errCode,proto3" json:"errCode,omitempty"`
	ErrMsg  string `protobuf:"bytes,2,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
}

func (x *CommonResp) Reset() {
	*x = CommonResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demo1_demo1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommonResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonResp) ProtoMessage() {}

func (x *CommonResp) ProtoReflect() protoreflect.Message {
	mi := &file_demo1_demo1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonResp.ProtoReflect.Descriptor instead.
func (*CommonResp) Descriptor() ([]byte, []int) {
	return file_demo1_demo1_proto_rawDescGZIP(), []int{0}
}

func (x *CommonResp) GetErrCode() int32 {
	if x != nil {
		return x.ErrCode
	}
	return 0
}

func (x *CommonResp) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

type GetFriendFromDBReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OperationID string `protobuf:"bytes,1,opt,name=OperationID,proto3" json:"OperationID,omitempty"`
}

func (x *GetFriendFromDBReq) Reset() {
	*x = GetFriendFromDBReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demo1_demo1_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFriendFromDBReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFriendFromDBReq) ProtoMessage() {}

func (x *GetFriendFromDBReq) ProtoReflect() protoreflect.Message {
	mi := &file_demo1_demo1_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFriendFromDBReq.ProtoReflect.Descriptor instead.
func (*GetFriendFromDBReq) Descriptor() ([]byte, []int) {
	return file_demo1_demo1_proto_rawDescGZIP(), []int{1}
}

func (x *GetFriendFromDBReq) GetOperationID() string {
	if x != nil {
		return x.OperationID
	}
	return ""
}

type GetFriendFromDBResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommonResp *CommonResp `protobuf:"bytes,1,opt,name=CommonResp,proto3" json:"CommonResp,omitempty"`
}

func (x *GetFriendFromDBResp) Reset() {
	*x = GetFriendFromDBResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demo1_demo1_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFriendFromDBResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFriendFromDBResp) ProtoMessage() {}

func (x *GetFriendFromDBResp) ProtoReflect() protoreflect.Message {
	mi := &file_demo1_demo1_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFriendFromDBResp.ProtoReflect.Descriptor instead.
func (*GetFriendFromDBResp) Descriptor() ([]byte, []int) {
	return file_demo1_demo1_proto_rawDescGZIP(), []int{2}
}

func (x *GetFriendFromDBResp) GetCommonResp() *CommonResp {
	if x != nil {
		return x.CommonResp
	}
	return nil
}

type GetFriendFromRedisReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OperationID string `protobuf:"bytes,1,opt,name=OperationID,proto3" json:"OperationID,omitempty"`
}

func (x *GetFriendFromRedisReq) Reset() {
	*x = GetFriendFromRedisReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demo1_demo1_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFriendFromRedisReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFriendFromRedisReq) ProtoMessage() {}

func (x *GetFriendFromRedisReq) ProtoReflect() protoreflect.Message {
	mi := &file_demo1_demo1_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFriendFromRedisReq.ProtoReflect.Descriptor instead.
func (*GetFriendFromRedisReq) Descriptor() ([]byte, []int) {
	return file_demo1_demo1_proto_rawDescGZIP(), []int{3}
}

func (x *GetFriendFromRedisReq) GetOperationID() string {
	if x != nil {
		return x.OperationID
	}
	return ""
}

type GetFriendFromRedisResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommonResp *CommonResp `protobuf:"bytes,1,opt,name=CommonResp,proto3" json:"CommonResp,omitempty"`
}

func (x *GetFriendFromRedisResp) Reset() {
	*x = GetFriendFromRedisResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demo1_demo1_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFriendFromRedisResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFriendFromRedisResp) ProtoMessage() {}

func (x *GetFriendFromRedisResp) ProtoReflect() protoreflect.Message {
	mi := &file_demo1_demo1_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFriendFromRedisResp.ProtoReflect.Descriptor instead.
func (*GetFriendFromRedisResp) Descriptor() ([]byte, []int) {
	return file_demo1_demo1_proto_rawDescGZIP(), []int{4}
}

func (x *GetFriendFromRedisResp) GetCommonResp() *CommonResp {
	if x != nil {
		return x.CommonResp
	}
	return nil
}

type GetFriendFromLocalCacheReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OperationID string `protobuf:"bytes,1,opt,name=OperationID,proto3" json:"OperationID,omitempty"`
}

func (x *GetFriendFromLocalCacheReq) Reset() {
	*x = GetFriendFromLocalCacheReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demo1_demo1_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFriendFromLocalCacheReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFriendFromLocalCacheReq) ProtoMessage() {}

func (x *GetFriendFromLocalCacheReq) ProtoReflect() protoreflect.Message {
	mi := &file_demo1_demo1_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFriendFromLocalCacheReq.ProtoReflect.Descriptor instead.
func (*GetFriendFromLocalCacheReq) Descriptor() ([]byte, []int) {
	return file_demo1_demo1_proto_rawDescGZIP(), []int{5}
}

func (x *GetFriendFromLocalCacheReq) GetOperationID() string {
	if x != nil {
		return x.OperationID
	}
	return ""
}

type GetFriendFromLocalCacheResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommonResp *CommonResp `protobuf:"bytes,1,opt,name=CommonResp,proto3" json:"CommonResp,omitempty"`
}

func (x *GetFriendFromLocalCacheResp) Reset() {
	*x = GetFriendFromLocalCacheResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demo1_demo1_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFriendFromLocalCacheResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFriendFromLocalCacheResp) ProtoMessage() {}

func (x *GetFriendFromLocalCacheResp) ProtoReflect() protoreflect.Message {
	mi := &file_demo1_demo1_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFriendFromLocalCacheResp.ProtoReflect.Descriptor instead.
func (*GetFriendFromLocalCacheResp) Descriptor() ([]byte, []int) {
	return file_demo1_demo1_proto_rawDescGZIP(), []int{6}
}

func (x *GetFriendFromLocalCacheResp) GetCommonResp() *CommonResp {
	if x != nil {
		return x.CommonResp
	}
	return nil
}

var File_demo1_demo1_proto protoreflect.FileDescriptor

var file_demo1_demo1_proto_rawDesc = []byte{
	0x0a, 0x11, 0x64, 0x65, 0x6d, 0x6f, 0x31, 0x2f, 0x64, 0x65, 0x6d, 0x6f, 0x31, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x64, 0x65, 0x6d, 0x6f, 0x31, 0x22, 0x3e, 0x0a, 0x0a, 0x43, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x72, 0x72, 0x43,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x65, 0x72, 0x72, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x4d, 0x73, 0x67, 0x22, 0x36, 0x0a, 0x12, 0x47, 0x65,
	0x74, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x46, 0x72, 0x6f, 0x6d, 0x44, 0x42, 0x52, 0x65, 0x71,
	0x12, 0x20, 0x0a, 0x0b, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x49, 0x44, 0x22, 0x48, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x46,
	0x72, 0x6f, 0x6d, 0x44, 0x42, 0x52, 0x65, 0x73, 0x70, 0x12, 0x31, 0x0a, 0x0a, 0x43, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x64, 0x65, 0x6d, 0x6f, 0x31, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x52, 0x0a, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x22, 0x39, 0x0a, 0x15,
	0x47, 0x65, 0x74, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x46, 0x72, 0x6f, 0x6d, 0x52, 0x65, 0x64,
	0x69, 0x73, 0x52, 0x65, 0x71, 0x12, 0x20, 0x0a, 0x0b, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x4f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x22, 0x4b, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x46, 0x72,
	0x69, 0x65, 0x6e, 0x64, 0x46, 0x72, 0x6f, 0x6d, 0x52, 0x65, 0x64, 0x69, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x31, 0x0a, 0x0a, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x31, 0x2e, 0x43, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x52, 0x0a, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x22, 0x3e, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x46, 0x72, 0x69, 0x65, 0x6e,
	0x64, 0x46, 0x72, 0x6f, 0x6d, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x43, 0x61, 0x63, 0x68, 0x65, 0x52,
	0x65, 0x71, 0x12, 0x20, 0x0a, 0x0b, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x44, 0x22, 0x50, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x46, 0x72, 0x69, 0x65, 0x6e,
	0x64, 0x46, 0x72, 0x6f, 0x6d, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x43, 0x61, 0x63, 0x68, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x31, 0x0a, 0x0a, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x31, 0x2e,
	0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x52, 0x0a, 0x43, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x32, 0x8d, 0x02, 0x0a, 0x0c, 0x63, 0x68, 0x61, 0x69, 0x6e,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x48, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x46, 0x72,
	0x69, 0x65, 0x6e, 0x64, 0x46, 0x72, 0x6f, 0x6d, 0x44, 0x42, 0x12, 0x19, 0x2e, 0x64, 0x65, 0x6d,
	0x6f, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x46, 0x72, 0x6f, 0x6d,
	0x44, 0x42, 0x52, 0x65, 0x71, 0x1a, 0x1a, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x31, 0x2e, 0x47, 0x65,
	0x74, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x46, 0x72, 0x6f, 0x6d, 0x44, 0x42, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x51, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x46, 0x72,
	0x6f, 0x6d, 0x52, 0x65, 0x64, 0x69, 0x73, 0x12, 0x1c, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x31, 0x2e,
	0x47, 0x65, 0x74, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x46, 0x72, 0x6f, 0x6d, 0x52, 0x65, 0x64,
	0x69, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x1d, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x31, 0x2e, 0x47, 0x65,
	0x74, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x46, 0x72, 0x6f, 0x6d, 0x52, 0x65, 0x64, 0x69, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x60, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x46, 0x72, 0x69, 0x65, 0x6e,
	0x64, 0x46, 0x72, 0x6f, 0x6d, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x43, 0x61, 0x63, 0x68, 0x65, 0x12,
	0x21, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x72, 0x69, 0x65, 0x6e,
	0x64, 0x46, 0x72, 0x6f, 0x6d, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x43, 0x61, 0x63, 0x68, 0x65, 0x52,
	0x65, 0x71, 0x1a, 0x22, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x72,
	0x69, 0x65, 0x6e, 0x64, 0x46, 0x72, 0x6f, 0x6d, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x43, 0x61, 0x63,
	0x68, 0x65, 0x52, 0x65, 0x73, 0x70, 0x42, 0x08, 0x5a, 0x06, 0x2f, 0x64, 0x65, 0x6d, 0x6f, 0x31,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_demo1_demo1_proto_rawDescOnce sync.Once
	file_demo1_demo1_proto_rawDescData = file_demo1_demo1_proto_rawDesc
)

func file_demo1_demo1_proto_rawDescGZIP() []byte {
	file_demo1_demo1_proto_rawDescOnce.Do(func() {
		file_demo1_demo1_proto_rawDescData = protoimpl.X.CompressGZIP(file_demo1_demo1_proto_rawDescData)
	})
	return file_demo1_demo1_proto_rawDescData
}

var file_demo1_demo1_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_demo1_demo1_proto_goTypes = []interface{}{
	(*CommonResp)(nil),                  // 0: demo1.CommonResp
	(*GetFriendFromDBReq)(nil),          // 1: demo1.GetFriendFromDBReq
	(*GetFriendFromDBResp)(nil),         // 2: demo1.GetFriendFromDBResp
	(*GetFriendFromRedisReq)(nil),       // 3: demo1.GetFriendFromRedisReq
	(*GetFriendFromRedisResp)(nil),      // 4: demo1.GetFriendFromRedisResp
	(*GetFriendFromLocalCacheReq)(nil),  // 5: demo1.GetFriendFromLocalCacheReq
	(*GetFriendFromLocalCacheResp)(nil), // 6: demo1.GetFriendFromLocalCacheResp
}
var file_demo1_demo1_proto_depIdxs = []int32{
	0, // 0: demo1.GetFriendFromDBResp.CommonResp:type_name -> demo1.CommonResp
	0, // 1: demo1.GetFriendFromRedisResp.CommonResp:type_name -> demo1.CommonResp
	0, // 2: demo1.GetFriendFromLocalCacheResp.CommonResp:type_name -> demo1.CommonResp
	1, // 3: demo1.chainService.GetFriendFromDB:input_type -> demo1.GetFriendFromDBReq
	3, // 4: demo1.chainService.GetFriendFromRedis:input_type -> demo1.GetFriendFromRedisReq
	5, // 5: demo1.chainService.GetFriendFromLocalCache:input_type -> demo1.GetFriendFromLocalCacheReq
	2, // 6: demo1.chainService.GetFriendFromDB:output_type -> demo1.GetFriendFromDBResp
	4, // 7: demo1.chainService.GetFriendFromRedis:output_type -> demo1.GetFriendFromRedisResp
	6, // 8: demo1.chainService.GetFriendFromLocalCache:output_type -> demo1.GetFriendFromLocalCacheResp
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_demo1_demo1_proto_init() }
func file_demo1_demo1_proto_init() {
	if File_demo1_demo1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_demo1_demo1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommonResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_demo1_demo1_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFriendFromDBReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_demo1_demo1_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFriendFromDBResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_demo1_demo1_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFriendFromRedisReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_demo1_demo1_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFriendFromRedisResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_demo1_demo1_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFriendFromLocalCacheReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_demo1_demo1_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFriendFromLocalCacheResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_demo1_demo1_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_demo1_demo1_proto_goTypes,
		DependencyIndexes: file_demo1_demo1_proto_depIdxs,
		MessageInfos:      file_demo1_demo1_proto_msgTypes,
	}.Build()
	File_demo1_demo1_proto = out.File
	file_demo1_demo1_proto_rawDesc = nil
	file_demo1_demo1_proto_goTypes = nil
	file_demo1_demo1_proto_depIdxs = nil
}
